### ISSUE TITLE
pending points not always updating on profile pages after swap has been closed.

### ISSUE THREAD

**Issue by glennfrutiz** [CS361-F2020/Project#61]
After a swap has been approved and closed, when checking points on the "Profile" sometimes pending points do not update. This goes for both the seller and requestor. 
Their available points still increase or decrease.
The source of the error must be the pending points function in common.js.

Steps to reproduce

login to bookswap.
request a book from the search page.
check the profile page of the requestor and seller to ensure pending points have been altered.
have the seller approve the request on the myswaps page.
mark the book as received on the requestor page on the myswaps page.
close the swap on both the requestor and seller myswaps page.
check the profile page of the requestor and seller and notice that the pending points have not changed.

**Comment by mkoeplin** [comment]
I've resolved this issue so that the profile page and requesting a book take into account the proper pending points and available point values. We can close this issue now!
