### ISSUE TITLE
google-books-search module doesn't recognize some books available through Google Books API

### ISSUE THREAD

**Issue by jung8** [CS361-F2020/Project#66]
When adding a book to a user's My Library page using the ISBN it is sometimes not found but when calling the Google Books API the book is found with the same ISBN. The npm package "google-books-search" seems to not recognize some books that are found by manually calling the Google Books API.

Steps to reproduce:

1. click the "add a book" button on the My Library page
2. using ISBN - 9780439064873 a book is not found but using www.googleapis.com/books the book is found

**Comment by mkoeplin** [comment]
The package is set to only search isbn fields and there is no match in google books with that isbn (even through the api). While the google book api wide open search returns results, if you look at the result set none of them actually have that isbn, it is just returning 'similar' results it thinks might be relevant. You can see the results here [https://www.googleapis.com/books/v1/volumes?q=%209780439064873] and a quick search on the page shows that none of the results have that isbn and the most relevant result is a coloring book. Currently the options set for the package are to only allow books to be returned and we only search fields that may contain isbn. If we were to remove these options, the google-books-search would also return the coloring book however we don't want that result as it doesn't have the correct isbn.

Closing this as it's not an issue.
